apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: for-sale-2
spec:
  hosts:
  - for-sale-2.games.internal
  scaleTargetRef:
    name: for-sale-2
    kind: Deployment
    apiVersion: apps/v1
    service: for-sale-2
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800
