#!/bin/bash

set -euo pipefail

docker run --rm -it -v "$(pwd)":/volume clux/muslrust bash -c 'cargo build --release && cargo test --release'
rm -rf lambda
mkdir lambda
cp target/x86_64-unknown-linux-musl/release/cli lambda/game
curl https://raw.githubusercontent.com/brdgme/lambda/master/index.js > lambda/index.js