---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: brdgme/api
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: postgres-config
          env:
            - name: ROCKET_ADDRESS
              value: "0.0.0.0"
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              memory: 128Mi
