---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: brdgme/api
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: postgres-config
