apiVersion: brdgme.com/v1
kind: GameVersion
metadata:
  name: zombie-dice-2
  namespace: brdgme
spec:
  typeName: Zombie Dice
  weight: 1.0
  blurb: "Shake the dice cup and eat brains, but stop before you collect three shotgun blasts. A quick zombie-themed push-your-luck dice game."
  interfaceVersion: 2
