---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleship-1
spec:
  selector:
    matchLabels:
      app: battleship-1
  template:
    metadata:
      labels:
        app: battleship-1
    spec:
      containers:
      - name: battleship-1
        image: brdgme/battleship-1
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
