apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: battleship-1
spec:
  hosts:
  - battleship-1.games.internal
  scaleTargetRef:
    name: battleship-1
    kind: Deployment
    apiVersion: apps/v1
    service: battleship-1
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
