apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: greed-1
spec:
  hosts:
  - greed-1.games.internal
  scaleTargetRef:
    name: greed-1
    kind: Deployment
    apiVersion: apps/v1
    service: greed-1
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
