matrix:
  include:
    - language: go
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
      script:
        - cd brdgme-go
        - go build ./...
        - go test ./...
        - golangci-lint run
    - language: rust
      before_script:
        - rustup component add clippy
      script:
        - cargo build
        - cargo test
        - cargo clippy -- -D warnings