language: generic

cache:
  directories:
    - /home/travis/.cache/bazel/
    - /root/.cache/bazel/

services:
  - docker

script:
- docker run --rm -v "$PWD":/usr/src/app insready/bazel /bin/bash -c "bazel build ... && bazel test ..."