apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: brdgme
build:
  local:
    useBuildkit: true
  artifacts:
  - image: brdgme/api
    docker:
      target: api
  - image: brdgme/web
    docker:
      target: web
  - image: brdgme/websocket
    docker:
      target: websocket
  - image: brdgme/acquire-1
    docker:
      target: acquire-1
  - image: brdgme/lost-cities-1
    docker:
      target: lost-cities-1
  - image: brdgme/lost-cities-2
    docker:
      target: lost-cities-2
  - image: brdgme/age-of-war-1
    docker:
      target: age-of-war-1
  - image: brdgme/liars-dice-1
    docker:
      target: liars-dice-1
  - image: brdgme/for-sale-1
    docker:
      target: for-sale-1
  - image: brdgme/roll-through-the-ages-1
    docker:
      target: roll-through-the-ages-1
deploy:
  kubectl:
    manifests:
    - k8s/api.yaml
    - k8s/web.yaml
    - k8s/websocket.yaml
    - k8s/game/acquire-1.yaml
    - k8s/game/lost-cities-1.yaml
    - k8s/game/lost-cities-2.yaml
    - k8s/game/age-of-war-1.yaml
    - k8s/game/liars-dice-1.yaml
    - k8s/game/for-sale-1.yaml
    - k8s/game/roll-through-the-ages-1.yaml