apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: brdgme
build:
  local:
    useBuildkit: true
  artifacts:
  # Games (Default build only includes games)
  - image: brdgme/acquire-1
    docker:
      dockerfile: rust/Dockerfile
      target: acquire-1
  - image: brdgme/age-of-war-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: age-of-war-1
  - image: brdgme/battleship-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: battleship-1
  - image: brdgme/category-5-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: category-5-1
  - image: brdgme/cathedral-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: cathedral-1
  - image: brdgme/farkle-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: farkle-1
  - image: brdgme/for-sale-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: for-sale-1
  - image: brdgme/greed-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: greed-1
  - image: brdgme/liars-dice-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: liars-dice-1
  - image: brdgme/lost-cities-1
    docker:
      dockerfile: rust/Dockerfile
      target: lost-cities-1
  - image: brdgme/lost-cities-2
    docker:
      dockerfile: rust/Dockerfile
      target: lost-cities-2
  - image: brdgme/love-letter-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: love-letter-1
  - image: brdgme/modern-art-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: modern-art-1
  - image: brdgme/no-thanks-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: no-thanks-1
  - image: brdgme/roll-through-the-ages-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: roll-through-the-ages-1
  - image: brdgme/splendor-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: splendor-1
  - image: brdgme/sushi-go-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: sushi-go-1
  - image: brdgme/sushizock-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: sushizock-1
  - image: brdgme/texas-holdem-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: texas-holdem-1
  - image: brdgme/zombie-dice-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: zombie-dice-1
deploy:
  kustomize:
    paths: ["k8s/dev-without-web"]
portForward:
  - resourceType: service
    resourceName: postgres
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: redis
    port: 6379
    localPort: 6379
  # Forward web if it exists (in with-web profile)
  - resourceType: service
    resourceName: web
    port: 80
    localPort: 8080
profiles:
- name: with-web
  build:
    artifacts:
    # Base services
    - image: brdgme/web
      docker:
        dockerfile: rust/Dockerfile
        target: web
    # Games
    - image: brdgme/acquire-1
      docker:
        dockerfile: rust/Dockerfile
        target: acquire-1
    - image: brdgme/age-of-war-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: age-of-war-1
    - image: brdgme/battleship-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: battleship-1
    - image: brdgme/category-5-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: category-5-1
    - image: brdgme/cathedral-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: cathedral-1
    - image: brdgme/farkle-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: farkle-1
    - image: brdgme/for-sale-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: for-sale-1
    - image: brdgme/greed-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: greed-1
    - image: brdgme/liars-dice-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: liars-dice-1
    - image: brdgme/lost-cities-1
      docker:
        dockerfile: rust/Dockerfile
        target: lost-cities-1
    - image: brdgme/lost-cities-2
      docker:
        dockerfile: rust/Dockerfile
        target: lost-cities-2
    - image: brdgme/love-letter-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: love-letter-1
    - image: brdgme/modern-art-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: modern-art-1
    - image: brdgme/no-thanks-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: no-thanks-1
    - image: brdgme/roll-through-the-ages-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: roll-through-the-ages-1
    - image: brdgme/splendor-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: splendor-1
    - image: brdgme/sushi-go-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: sushi-go-1
    - image: brdgme/sushizock-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: sushizock-1
    - image: brdgme/texas-holdem-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: texas-holdem-1
    - image: brdgme/zombie-dice-1
      docker:
        dockerfile: brdgme-go/Dockerfile
        target: zombie-dice-1
  deploy:
    kustomize:
      paths: ["k8s/dev"]
- name: prod
  deploy:
    kustomize:
      paths: ["k8s/prod"]