apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: brdgme
build:
  local:
    useBuildkit: true
    concurrency: 0
  artifacts:
  - image: brdgme/api
    docker:
      dockerfile: rust/Dockerfile
      target: api
  - image: brdgme/web
    docker:
      dockerfile: web/Dockerfile
      target: web
  - image: brdgme/websocket
    docker:
      dockerfile: websocket/Dockerfile
      target: websocket
  - image: brdgme/acquire-1
    docker:
      dockerfile: rust/Dockerfile
      target: acquire-1
  - image: brdgme/lost-cities-1
    docker:
      dockerfile: rust/Dockerfile
      target: lost-cities-1
  - image: brdgme/lost-cities-2
    docker:
      dockerfile: rust/Dockerfile
      target: lost-cities-2
  - image: brdgme/age-of-war-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: age-of-war-1
  - image: brdgme/liars-dice-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: liars-dice-1
  - image: brdgme/for-sale-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: for-sale-1
  - image: brdgme/roll-through-the-ages-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: roll-through-the-ages-1
  - image: brdgme/texas-holdem-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: texas-holdem-1
  - image: brdgme/modern-art-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: modern-art-1
  - image: brdgme/no-thanks-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: no-thanks-1
  - image: brdgme/sushizock-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: sushizock-1
  - image: brdgme/sushi-go-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: sushi-go-1
  - image: brdgme/zombie-dice-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: zombie-dice-1
  - image: brdgme/love-letter-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: love-letter-1
  - image: brdgme/category-5-1
    docker:
      dockerfile: brdgme-go/Dockerfile
      target: category-5-1
deploy:
  kubectl:
    manifests:
    - k8s/api.yaml
    - k8s/web.yaml
    - k8s/websocket.yaml
    - k8s/game/acquire-1.yaml
    - k8s/game/lost-cities-1.yaml
    - k8s/game/lost-cities-2.yaml
    - k8s/game/age-of-war-1.yaml
    - k8s/game/liars-dice-1.yaml
    - k8s/game/for-sale-1.yaml
    - k8s/game/roll-through-the-ages-1.yaml
    - k8s/game/texas-holdem-1.yaml
    - k8s/game/modern-art-1.yaml
    - k8s/game/no-thanks-1.yaml
    - k8s/game/sushizock-1.yaml
    - k8s/game/sushi-go-1.yaml
    - k8s/game/zombie-dice-1.yaml
    - k8s/game/love-letter-1.yaml
    - k8s/game/category-5-1.yaml