---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cathedral-1
spec:
  selector:
    matchLabels:
      app: cathedral-1
  template:
    metadata:
      labels:
        app: cathedral-1
    spec:
      containers:
      - name: cathedral-1
        image: brdgme/cathedral-1
        ports:
        - containerPort: 80
