namespace: brdgme
bases:
- ../../base/brdgme
- ../../base/gateway
- ../alloy
resources:
- postgres-backup.yaml
patches:
- path: postgres-patch.yaml
- path: web-patch.yaml
images:
- name: brdgme/migrate
  newName: ghcr.io/brdgme/brdgme/migrate
  newTag: latest
- name: brdgme/web
  newName: ghcr.io/brdgme/brdgme/web
  newTag: latest
- name: brdgme/web-legacy
  newName: ghcr.io/brdgme/brdgme/web-legacy
  newTag: latest
- name: brdgme/websocket
  newName: ghcr.io/brdgme/brdgme/websocket
  newTag: latest
- name: brdgme/api
  newName: ghcr.io/brdgme/brdgme/api
  newTag: latest
- name: brdgme/bot
  newName: ghcr.io/brdgme/brdgme/bot
  newTag: latest
- name: brdgme/operator
  newName: ghcr.io/brdgme/brdgme/operator
  newTag: latest
- name: brdgme/acquire-1
  newName: ghcr.io/brdgme/brdgme/acquire-1
  newTag: latest
- name: brdgme/lost-cities-1
  newName: ghcr.io/brdgme/brdgme/lost-cities-1
  newTag: latest
- name: brdgme/lost-cities-2
  newName: ghcr.io/brdgme/brdgme/lost-cities-2
  newTag: latest
- name: brdgme/age-of-war-1
  newName: ghcr.io/brdgme/brdgme/age-of-war-1
  newTag: latest
- name: brdgme/battleship-1
  newName: ghcr.io/brdgme/brdgme/battleship-1
  newTag: latest
- name: brdgme/battleship-2
  newName: ghcr.io/brdgme/brdgme/battleship-2
  newTag: latest
- name: brdgme/category-5-1
  newName: ghcr.io/brdgme/brdgme/category-5-1
  newTag: latest
- name: brdgme/category-5-2
  newName: ghcr.io/brdgme/brdgme/category-5-2
  newTag: latest
- name: brdgme/cathedral-1
  newName: ghcr.io/brdgme/brdgme/cathedral-1
  newTag: latest
- name: brdgme/farkle-1
  newName: ghcr.io/brdgme/brdgme/farkle-1
  newTag: latest
- name: brdgme/farkle-2
  newName: ghcr.io/brdgme/brdgme/farkle-2
  newTag: latest
- name: brdgme/for-sale-1
  newName: ghcr.io/brdgme/brdgme/for-sale-1
  newTag: latest
- name: brdgme/for-sale-2
  newName: ghcr.io/brdgme/brdgme/for-sale-2
  newTag: latest
- name: brdgme/greed-1
  newName: ghcr.io/brdgme/brdgme/greed-1
  newTag: latest
- name: brdgme/greed-2
  newName: ghcr.io/brdgme/brdgme/greed-2
  newTag: latest
- name: brdgme/liars-dice-1
  newName: ghcr.io/brdgme/brdgme/liars-dice-1
  newTag: latest
- name: brdgme/liars-dice-2
  newName: ghcr.io/brdgme/brdgme/liars-dice-2
  newTag: latest
- name: brdgme/love-letter-1
  newName: ghcr.io/brdgme/brdgme/love-letter-1
  newTag: latest
- name: brdgme/modern-art-1
  newName: ghcr.io/brdgme/brdgme/modern-art-1
  newTag: latest
- name: brdgme/no-thanks-1
  newName: ghcr.io/brdgme/brdgme/no-thanks-1
  newTag: latest
- name: brdgme/no-thanks-2
  newName: ghcr.io/brdgme/brdgme/no-thanks-2
  newTag: latest
- name: brdgme/roll-through-the-ages-1
  newName: ghcr.io/brdgme/brdgme/roll-through-the-ages-1
  newTag: latest
- name: brdgme/splendor-1
  newName: ghcr.io/brdgme/brdgme/splendor-1
  newTag: latest
- name: brdgme/sushi-go-1
  newName: ghcr.io/brdgme/brdgme/sushi-go-1
  newTag: latest
- name: brdgme/sushi-go-2
  newName: ghcr.io/brdgme/brdgme/sushi-go-2
  newTag: latest
- name: brdgme/sushizock-1
  newName: ghcr.io/brdgme/brdgme/sushizock-1
  newTag: latest
- name: brdgme/sushizock-2
  newName: ghcr.io/brdgme/brdgme/sushizock-2
  newTag: latest
- name: brdgme/texas-holdem-1
  newName: ghcr.io/brdgme/brdgme/texas-holdem-1
  newTag: latest
- name: brdgme/zombie-dice-1
  newName: ghcr.io/brdgme/brdgme/zombie-dice-1
  newTag: latest
- name: brdgme/zombie-dice-2
  newName: ghcr.io/brdgme/brdgme/zombie-dice-2
  newTag: latest
