namespace: brdgme
bases:
- ../../base/brdgme
images:
- name: brdgme/web
  newName: ghcr.io/beefsack/brdgme/web
  newTag: latest
- name: brdgme/web-legacy
  newName: ghcr.io/beefsack/brdgme/web-legacy
  newTag: latest
- name: brdgme/websocket
  newName: ghcr.io/beefsack/brdgme/websocket
  newTag: latest
- name: brdgme/api
  newName: ghcr.io/beefsack/brdgme/api
  newTag: latest
- name: brdgme/acquire-1
  newName: ghcr.io/beefsack/brdgme/acquire-1
  newTag: latest
- name: brdgme/lost-cities-1
  newName: ghcr.io/beefsack/brdgme/lost-cities-1
  newTag: latest
- name: brdgme/lost-cities-2
  newName: ghcr.io/beefsack/brdgme/lost-cities-2
  newTag: latest
- name: brdgme/age-of-war-1
  newName: ghcr.io/beefsack/brdgme/age-of-war-1
  newTag: latest
- name: brdgme/battleship-1
  newName: ghcr.io/beefsack/brdgme/battleship-1
  newTag: latest
- name: brdgme/category-5-1
  newName: ghcr.io/beefsack/brdgme/category-5-1
  newTag: latest
- name: brdgme/cathedral-1
  newName: ghcr.io/beefsack/brdgme/cathedral-1
  newTag: latest
- name: brdgme/farkle-1
  newName: ghcr.io/beefsack/brdgme/farkle-1
  newTag: latest
- name: brdgme/for-sale-1
  newName: ghcr.io/beefsack/brdgme/for-sale-1
  newTag: latest
- name: brdgme/greed-1
  newName: ghcr.io/beefsack/brdgme/greed-1
  newTag: latest
- name: brdgme/liars-dice-1
  newName: ghcr.io/beefsack/brdgme/liars-dice-1
  newTag: latest
- name: brdgme/love-letter-1
  newName: ghcr.io/beefsack/brdgme/love-letter-1
  newTag: latest
- name: brdgme/modern-art-1
  newName: ghcr.io/beefsack/brdgme/modern-art-1
  newTag: latest
- name: brdgme/no-thanks-1
  newName: ghcr.io/beefsack/brdgme/no-thanks-1
  newTag: latest
- name: brdgme/roll-through-the-ages-1
  newName: ghcr.io/beefsack/brdgme/roll-through-the-ages-1
  newTag: latest
- name: brdgme/splendor-1
  newName: ghcr.io/beefsack/brdgme/splendor-1
  newTag: latest
- name: brdgme/sushi-go-1
  newName: ghcr.io/beefsack/brdgme/sushi-go-1
  newTag: latest
- name: brdgme/sushizock-1
  newName: ghcr.io/beefsack/brdgme/sushizock-1
  newTag: latest
- name: brdgme/texas-holdem-1
  newName: ghcr.io/beefsack/brdgme/texas-holdem-1
  newTag: latest
- name: brdgme/zombie-dice-1
  newName: ghcr.io/beefsack/brdgme/zombie-dice-1
  newTag: latest
