---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: for-sale-1
spec:
  selector:
    matchLabels:
      app: for-sale-1
  template:
    metadata:
      labels:
        app: for-sale-1
    spec:
      containers:
      - name: for-sale-1
        image: brdgme/for-sale-1
        ports:
        - containerPort: 80
