apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: texas-holdem-1
spec:
  hosts:
  - texas-holdem-1.games.internal
  scaleTargetRef:
    name: texas-holdem-1
    kind: Deployment
    apiVersion: apps/v1
    service: texas-holdem-1
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
