---
apiVersion: v1
kind: Service
metadata:
  name: texas-holdem-1
  labels:
    app: texas-holdem-1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: texas-holdem-1
