---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splendor-1
spec:
  selector:
    matchLabels:
      app: splendor-1
  template:
    metadata:
      labels:
        app: splendor-1
    spec:
      containers:
      - name: splendor-1
        image: brdgme/splendor-1
        ports:
        - containerPort: 80
