---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: legacy.brdg.me
  annotations:
    networking.knative.dev/certificate-class: cert-manager.io
spec:
  ref:
    name: web-legacy
    kind: Service
    apiVersion: serving.knative.dev/v1
