[package]
name = "brdgme_render_plain"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true

[[bin]]
name = "render_plain"
path = "src/main.rs"

[dependencies]
brdgme_color = { path = "../../lib/color" }
brdgme_markup = { path = "../../lib/markup" }

[lints]
workspace = true
