[package]
name = "brdgme_fuzz"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]
edition = "2018"

[dependencies]
brdgme_cmd = { path = "../../lib/cmd" }
brdgme_game = { path = "../../lib/game" }
brdgme_rand_bot = { path = "../../lib/rand_bot" }
failure = "0.1.5"
num_cpus = "1.10.1"
rand = "0.6.5"
serde = "1.0.92"
