[package]
name = "no-thanks-2"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
brdgme_cmd = { path = "../../lib/cmd" }
brdgme_fuzz = { path = "../../tools/fuzz" }
brdgme_color = { path = "../../lib/color" }
brdgme_game = { path = "../../lib/game" }
brdgme_markup = { path = "../../lib/markup" }
rand.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
brdgme_cmd = { path = "../../lib/cmd", features = ["test-support"] }

[lints]
workspace = true
