---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: brdgme/api:v1.30.0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  ports:
   - port: 8000
  selector:
   app: api