apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: websocket
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: brdgme/websocket
          env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "Go Sample v1"
