apiVersion: brdgme.com/v1
kind: GameVersion
metadata:
  name: acquire-1
  namespace: brdgme
spec:
  typeName: Acquire
  weight: 2.5
  blurb: "Build hotel chains, trigger lucrative mergers, and invest in the stock of the chains most likely to grow. A classic economic strategy game of timing and majority shareholding."
  interfaceVersion: 2
