---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liars-dice-1
spec:
  selector:
    matchLabels:
      app: liars-dice-1
  template:
    metadata:
      labels:
        app: liars-dice-1
    spec:
      containers:
      - name: liars-dice-1
        image: brdgme/liars-dice-1
        env:
        - name: ADDR
          value: "0.0.0.0:8080"
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
