apiVersion: brdgme.com/v1
kind: GameVersion
metadata:
  name: liars-dice-1
  namespace: brdgme
spec:
  typeName: Liar's Dice
  weight: 1.0
  blurb: "Bid on the dice hidden under everyone's cups, bluffing and calling bluffs until someone is caught out. Lose dice when you are wrong; the last player still rolling wins."
  isDeprecated: true
