apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: liars-dice-1
spec:
  hosts:
  - liars-dice-1.games.internal
  scaleTargetRef:
    name: liars-dice-1
    kind: Deployment
    apiVersion: apps/v1
    service: liars-dice-1
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800
