apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: sushizock-2
spec:
  hosts:
  - sushizock-2.games.internal
  scaleTargetRef:
    name: sushizock-2
    kind: Deployment
    apiVersion: apps/v1
    service: sushizock-2
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800
