---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: love-letter-1
spec:
  selector:
    matchLabels:
      app: love-letter-1
  template:
    metadata:
      labels:
        app: love-letter-1
    spec:
      containers:
      - name: love-letter-1
        image: brdgme/love-letter-1
        ports:
        - containerPort: 80
