---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: farkle-1
spec:
  selector:
    matchLabels:
      app: farkle-1
  template:
    metadata:
      labels:
        app: farkle-1
    spec:
      containers:
      - name: farkle-1
        image: brdgme/farkle-1
        ports:
        - containerPort: 80
