apiVersion: brdgme.com/v1
kind: GameVersion
metadata:
  name: age-of-war-2
  namespace: brdgme
spec:
  typeName: Age of War
  weight: 1.0
  blurb: "Roll dice to muster armies and conquer the castles of feudal Japan, stealing them from rivals until the clans are decided. A quick push-your-luck dice game."
  interfaceVersion: 2