---
apiVersion: v1
kind: Service
metadata:
  name: age-of-war-2
  labels:
    app: age-of-war-2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: age-of-war-2