---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-5-1
spec:
  selector:
    matchLabels:
      app: category-5-1
  template:
    metadata:
      labels:
        app: category-5-1
    spec:
      containers:
      - name: category-5-1
        image: brdgme/category-5-1
        ports:
        - containerPort: 80
