---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-legacy
  labels:
    app: web-legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-legacy
  template:
    metadata:
      labels:
        app: web-legacy
    spec:
      containers:
        - name: web-legacy
          image: brdgme/web-legacy
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
