apiVersion: brdgme.com/v1
kind: GameVersion
metadata:
  name: modern-art-2
  namespace: brdgme
spec:
  typeName: Modern Art
  weight: 2.0
  blurb: "Buy and sell paintings at auction, riding the market for the season's most fashionable artists. A classic auction game of valuation and salesmanship."
