---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roll-through-the-ages-1
spec:
  selector:
    matchLabels:
      app: roll-through-the-ages-1
  template:
    metadata:
      labels:
        app: roll-through-the-ages-1
    spec:
      containers:
      - name: roll-through-the-ages-1
        image: brdgme/roll-through-the-ages-1
        ports:
        - containerPort: 80
