apiVersion: brdgme.com/v1
kind: GameVersion
metadata:
  name: roll-through-the-ages-1
  namespace: brdgme
spec:
  typeName: Roll Through the Ages
  weight: 1.5
  blurb: "Roll dice to feed your people, raise monuments, and research developments through the Bronze Age. A quick civilization-building dice game."
  isDeprecated: true
