---
apiVersion: v1
kind: Service
metadata:
  name: roll-through-the-ages-1
  labels:
    app: roll-through-the-ages-1
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: roll-through-the-ages-1
