[package]
name = "lost-cities-2"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]
edition = "2024"

[dependencies]
brdgme_cmd = { path = "../../lib/cmd" }
brdgme_fuzz = { path = "../../tools/fuzz" }
brdgme_color = { path = "../../lib/color" }
brdgme_game = { path = "../../lib/game" }
brdgme_markup = { path = "../../lib/markup" }
rand = "0.9.0"
serde = { version = "1.0.114", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
