---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zombie-dice-1
spec:
  selector:
    matchLabels:
      app: zombie-dice-1
  template:
    metadata:
      labels:
        app: zombie-dice-1
    spec:
      containers:
      - name: zombie-dice-1
        image: brdgme/zombie-dice-1
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
