apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: sushi-go-1
spec:
  hosts:
  - sushi-go-1.games.internal
  scaleTargetRef:
    name: sushi-go-1
    kind: Deployment
    apiVersion: apps/v1
    service: sushi-go-1
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800
