---
apiVersion: v1
kind: Service
metadata:
  name: starship-catan-1
  labels:
    app: starship-catan-1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: starship-catan-1
