[workspace]
resolver = "2"

members = [
    "api",
    "game/acquire-1",
    "game/lords-of-vegas-1",
    "game/lost-cities-1",
    "game/lost-cities-2",
    "lib/cmd",
    "lib/color",
    "lib/game",
    "lib/markup",
    "lib/rand_bot",
    "tools/fuzz",
    "tools/repl",
]

[build]
rustflags = ["-g"]
