[workspace]

members = [
    "api",
    "game/acquire",
    "game/lords-of-vegas",
    "game/lost-cities",
    "game/lost-cities-1",
    "lib/cmd",
    "lib/color",
    "lib/game",
    "lib/markup",
    "lib/rand_bot",
    "tools/fuzz",
    "tools/repl",
]
