---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lost-cities-2
spec:
  selector:
    matchLabels:
      app: lost-cities-2
  template:
    metadata:
      labels:
        app: lost-cities-2
    spec:
      containers:
      - name: lost-cities-2
        image: brdgme/lost-cities-2
        ports:
        - containerPort: 80
