apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: lost-cities-2
spec:
  hosts:
  - lost-cities-2.games.internal
  scaleTargetRef:
    name: lost-cities-2
    kind: Deployment
    apiVersion: apps/v1
    service: lost-cities-2
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800
