---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sushizock-1
spec:
  selector:
    matchLabels:
      app: sushizock-1
  template:
    metadata:
      labels:
        app: sushizock-1
    spec:
      containers:
      - name: sushizock-1
        image: brdgme/sushizock-1
        ports:
        - containerPort: 80
