apiVersion: brdgme.com/v1
kind: GameVersion
metadata:
  name: sushizock-1
  namespace: brdgme
spec:
  typeName: Sushizock im Gockelwok
  weight: 1.0
  blurb: "Roll dice to grab tasty sushi tiles and dodge the fish bones, stealing from rivals when the dice allow. A push-your-luck tile-snatching dice game."
  isDeprecated: true
