apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: sushizock-1
spec:
  hosts:
  - sushizock-1.games.internal
  scaleTargetRef:
    name: sushizock-1
    kind: Deployment
    apiVersion: apps/v1
    service: sushizock-1
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800
