apiVersion: brdgme.com/v1
kind: GameVersion
metadata:
  name: cathedral-2
  namespace: brdgme
spec:
  typeName: Cathedral
  weight: 1.5
  blurb: "Place your buildings to wall off districts of a medieval city and squeeze out your opponent's pieces. An abstract territory battle for two."
  interfaceVersion: 2
