apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: no-thanks-2
spec:
  hosts:
  - no-thanks-2.games.internal
  scaleTargetRef:
    name: no-thanks-2
    kind: Deployment
    apiVersion: apps/v1
    service: no-thanks-2
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800
