bases:
- acquire-1
- alhambra-1
- age-of-war-1
- age-of-war-2
- battleship-1
- battleship-2
- category-5-1
- category-5-2
- cathedral-1
- cathedral-2
- farkle-1
- farkle-2
- for-sale-1
- for-sale-2
- greed-1
- greed-2
- jaipur-2
- liars-dice-1
- liars-dice-2
- lost-cities-1
- lost-cities-2
- love-letter-1
- love-letter-2
- modern-art-1
- modern-art-2
- no-thanks-1
- no-thanks-2
- red7-1
- roll-through-the-ages-1
- roll-through-the-ages-2
- seven-wonders-1
- splendor-1
- splendor-2
- starship-catan-1
- sushi-go-1
- sushi-go-2
- sushizock-1
- sushizock-2
- texas-holdem-1
- texas-holdem-2
- tic-tac-toe-2
- zombie-dice-1
- zombie-dice-2
