apiVersion: brdgme.com/v1
kind: GameVersion
metadata:
  name: texas-holdem-2
  namespace: brdgme
spec:
  typeName: "Texas Hold'em"
  weight: 2.0
  blurb: "No-limit Texas hold'em poker: bet, bluff, and go all-in to take every chip at the table."
