---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  serviceName: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.11-alpine
          args:
            - "-js"
            - "-sd"
            - "/data"
            - "-m"
            - "8222"
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitor
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8222
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8222
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
