---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: brdgme/bot
          envFrom:
            - secretRef:
                name: postgres-config
            - secretRef:
                name: bot-config
          env:
            - name: NATS_URL
              value: nats://nats:4222
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              memory: 128Mi
