language: go
before_deploy:
- mkdir lambda
- go build -o lambda/game cmd/*.go
- curl https://raw.githubusercontent.com/brdgme/lambda/master/index.js > lambda/index.js
deploy:
  provider: lambda
  function_name: age-of-war
  region: us-west-2
  role: arn:aws:iam::161480335654:role/brdgme-game
  runtime: "nodejs8.10"
  handler_name: handler
  access_key_id:
    secure: Ran8hQjP0B0Bip6qs8Yp2CjACPH66vpCrHPoT/FZAarcYgm+kXwXN08p0RYmO0sKCe4i0rN3RpV9uJpZeKYqSEi+XY24YNtAOlyBZqrF0HBUJJAvCi0exvHStyCoB12Uq9gdefpEPo3QRJEJK+NPgFJMUoFj6Xy6Yk+NrYMugBCQdmNu9U6yKSOF0Pky7594e8cgLSiXfSVkOexdLl+0zEQaLJz1zr/gInfdOcLMtGW/GiHqFCOHwm+2mRdmbUjdvLTUJiqUAAwyZ79T3yWzufaT41poTVQyT44fL1RemGZC0n3NtUo7o669uBhonbMn2UcVGT/0CMfTT+btnHA5mXBdqLGuanoZKBWpKZNPQM7ohaqlArz++y9HJTlzyv8wWJuoWigNRxU+yZFqvwNtJPREMA4TFJaY8qLqmTc58BnHnQggCZV9aHmuJGQC/ZuPoDjP2r6FylBI5F+XnvUoPVnEB+NnRuSfcX52Dz+r5DEBjjyxPJTUcYeSibX3c5VW4D3HmCcsU3qqSlYZ3u+XtNhlzGYyn0GYF/66mrSq7VleZWuJt2oyF4hG0GGqpiZgWZjXUqlt8kNjtxeysbzpSCTfra79k5oyu7+Zhgw34s6OxjpHdsn+XDk84h/ulldXkdR8IVMIPSGzO6+Dv5hEGtj+EEILqXpxhWqcqd62G5E=
  secret_access_key:
    secure: HWAuF/HPaMDdLzhdgjkWKpzVEXyUYmZeBkkFmhpFYBW1wWBOCcCrg0sFom0hi/bcQpaE69giqK0te0M2fPCeApipSqgvtUIyGY7dwr8OPmQjdIJTpVTY/nnbgB+OgJOy0Uh57/B/7rZ2amqVoObQ4g4UYa9cevw0PWCEsUhDaj1H+inj6whoYTm+sTtoQiwCrHc4iz232cdzsUC9k0MowASrJDMUFzbddHM3EkZzluwDySmCKUKTP5qQ6Ldv3nIDrrsZ99aC4uUeeFA522NANL+/C07Z8WOfq8VDRpEgVEhB7FqCX5WNcNQar92TnQFO0g98QhKZJFmVfvAhmEswi2uEcn37j9a8oxaEPj4B0+FsFUOmAz69glJg11WWUP0eik8O04loVSCZPJ57klqZKOCo6Lw+qzfsYuuPVwKd0IJscIiplrI1tYYXZKt7Lpa21F6FJmq4TNxXGEycJ6PrNNdCA27TgU6tOpE8KEaBWeJm0FIdvcuW21wFD82JfeCgdmeHCQALB0NboNz0XeksUMC61lkRw9cJ7BEtTl+B+I1d2HfiBSJR0yNUG9DJPw2CR/YtlxYeGsX539WChNU1bTGSRZJloWKijed+7cnw/Qh9KzgqHl8d1Ma6lDJoNIQ8b/yWEu84nvv0s6HmTH3vrVC2y0F/N4sswM2F2yHKi90=
  publish: true
  skip_cleanup: true
  zip: lambda
