apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: love-letter-2
spec:
  hosts:
  - love-letter-2.games.internal
  scaleTargetRef:
    name: love-letter-2
    kind: Deployment
    apiVersion: apps/v1
    service: love-letter-2
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800
