[package]
name = "brdgme_api"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]
edition = "2018"

[dependencies]
brdgme_cmd = { path = "../lib/cmd" }
brdgme_game = { path = "../lib/game" }
brdgme_color = { path = "../lib/color" }
brdgme_markup = { path = "../lib/markup" }
lazy_static = "1.4.0"
r2d2 = "0.8.9"
rand = "0.7.3"
chrono = "0.4.13"
lettre = "0.9.3"
lettre_email = "0.9.4"
log = "0.4.11"
env_logger = "0.7.1"
uuid = { version = "0.6.5", features = ["serde", "v4"] }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "e531770989ebf9c83b9d815520a3a269337c7a88" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "e531770989ebf9c83b9d815520a3a269337c7a88" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "e531770989ebf9c83b9d815520a3a269337c7a88", features = ["json"] }
email = "0.0.21"
hyper = "0.13.7"
hyper-tls = "0.4.3"
hyper-rustls = "0.21.0"
diesel = { version = "1.4.5", features = ["postgres", "uuid", "chrono", "32-column-tables"] }
r2d2-diesel = "1.0.0"
unicase = "2.6.0"
redis = "0.17.0"
anyhow = "1.0.32"
thiserror = "1.0.20"
bytes = "0.5.6"