---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acquire-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acquire-1
  template:
    metadata:
      labels:
        app: acquire-1
    spec:
      containers:
        - name: acquire
          image: brdgme/acquire-1:v1.8.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: acquire-1
  labels:
    app: acquire-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: acquire-1