---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleship-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: battleship-1
  template:
    metadata:
      labels:
        app: battleship-1
    spec:
      containers:
        - name: battleship
          image: brdgme/battleship-1:v1.38.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: battleship-1
  labels:
    app: battleship-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: battleship-1