---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-5-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-5-1
  template:
    metadata:
      labels:
        app: category-5-1
    spec:
      containers:
        - name: category-5
          image: brdgme/category-5-1:v1.29.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: category-5-1
  labels:
    app: category-5-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: category-5-1