---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cathedral-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cathedral-1
  template:
    metadata:
      labels:
        app: cathedral-1
    spec:
      containers:
        - name: cathedral
          image: brdgme/cathedral-1:v1.31.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cathedral-1
  labels:
    app: cathedral-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: cathedral-1