---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: for-sale-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: for-sale-1
  template:
    metadata:
      labels:
        app: for-sale-1
    spec:
      containers:
        - name: for-sale
          image: brdgme/for-sale-1:v1.9.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: for-sale-1
  labels:
    app: for-sale-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: for-sale-1