---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greed-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greed-1
  template:
    metadata:
      labels:
        app: greed-1
    spec:
      containers:
        - name: greed
          image: brdgme/greed-1:v1.38.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: greed-1
  labels:
    app: greed-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: greed-1