---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liars-dice-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liars-dice-1
  template:
    metadata:
      labels:
        app: liars-dice-1
    spec:
      containers:
        - name: liars-dice
          image: brdgme/liars-dice-1:v1.8.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: liars-dice-1
  labels:
    app: liars-dice-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: liars-dice-1