---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lost-cities-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lost-cities-1
  template:
    metadata:
      labels:
        app: lost-cities-1
    spec:
      containers:
        - name: lost-cities
          image: brdgme/lost-cities-1:v1.16.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lost-cities-1
  labels:
    app: lost-cities-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: lost-cities-1