---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: love-letter-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: love-letter-1
  template:
    metadata:
      labels:
        app: love-letter-1
    spec:
      containers:
        - name: love-letter
          image: brdgme/love-letter-1:v1.30.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: love-letter-1
  labels:
    app: love-letter-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: love-letter-1