---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-art-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modern-art-1
  template:
    metadata:
      labels:
        app: modern-art-1
    spec:
      containers:
        - name: modern-art
          image: brdgme/modern-art-1:v1.26.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: modern-art-1
  labels:
    app: modern-art-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: modern-art-1