---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-thanks-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-thanks-1
  template:
    metadata:
      labels:
        app: no-thanks-1
    spec:
      containers:
        - name: no-thanks
          image: brdgme/no-thanks-1:v1.23.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: no-thanks-1
  labels:
    app: no-thanks-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: no-thanks-1