---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roll-through-the-ages-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roll-through-the-ages-1
  template:
    metadata:
      labels:
        app: roll-through-the-ages-1
    spec:
      containers:
        - name: roll-through-the-ages
          image: brdgme/roll-through-the-ages-1:v1.21.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: roll-through-the-ages-1
  labels:
    app: roll-through-the-ages-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: roll-through-the-ages-1