---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splendor-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splendor-1
  template:
    metadata:
      labels:
        app: splendor-1
    spec:
      containers:
        - name: splendor
          image: brdgme/splendor-1:v1.37.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: splendor-1
  labels:
    app: splendor-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: splendor-1