---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sushizock-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sushizock-1
  template:
    metadata:
      labels:
        app: sushizock-1
    spec:
      containers:
        - name: sushizock
          image: brdgme/sushizock-1:v1.24.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sushizock-1
  labels:
    app: sushizock-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: sushizock-1