---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sushi-go-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sushi-go-1
  template:
    metadata:
      labels:
        app: sushi-go-1
    spec:
      containers:
        - name: sushi-go
          image: brdgme/sushi-go-1:v1.37.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sushi-go-1
  labels:
    app: sushi-go-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: sushi-go-1