---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: texas-holdem-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: texas-holdem-1
  template:
    metadata:
      labels:
        app: texas-holdem-1
    spec:
      containers:
        - name: texas-holdem
          image: brdgme/texas-holdem-1:v1.36.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: texas-holdem-1
  labels:
    app: texas-holdem-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: texas-holdem-1