---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zombie-dice-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zombie-dice-1
  template:
    metadata:
      labels:
        app: zombie-dice-1
    spec:
      containers:
        - name: zombie-dice
          image: brdgme/zombie-dice-1:v1.31.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zombie-dice-1
  labels:
    app: zombie-dice-1
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: zombie-dice-1