[package]
name = "brdgme_rand_bot"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
brdgme_cmd = { path = "../cmd" }
brdgme_game = { path = "../game" }
chrono = { version = "0.4.45", features = ["serde"] }
rand.workspace = true
serde_json.workspace = true

[lints]
workspace = true
