---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: brdgme/websocket
          ports:
            - containerPort: 80
