---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: websocket
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: websocket
          image: brdgme/websocket
          ports:
            - containerPort: 80
          env:
            - name: REDIS_URL
              value: "redis://redis"
