[package]
name = "brdgme_fuzz"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
brdgme_cmd = { path = "../../lib/cmd" }
brdgme_game = { path = "../../lib/game" }
brdgme_rand_bot = { path = "../../lib/rand_bot" }
anyhow.workspace = true
num_cpus = "1.17.0"
rand.workspace = true
serde.workspace = true

[lints]
workspace = true
