[package]
name = "brdgme_fuzz"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]
edition = "2024"

[dependencies]
brdgme_cmd = { path = "../../lib/cmd" }
brdgme_game = { path = "../../lib/game" }
brdgme_rand_bot = { path = "../../lib/rand_bot" }
anyhow = "1.0.32"
num_cpus = "1.13.0"
rand = "0.9.0"
serde = "1.0.114"
