language: node_js
before_deploy:
- npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: L89JbpkC9fmtkIOm2CGf35U1pAdCXgGc1wSOmJVkH/XYZymoW3RuUj7WyTaEZ4hBGPzm2WwfBeTgOgveMFMwsgllYegrzva3KjNe526KwB3UAiWEZkjxuzHU0yqp+RXpAT0VaXjNIgacWnSTe0jJgI5mGixnvS03mdyd77exMlvB2vrPIm8oFV/L24U9XKCMFBFhgRkeI3GnDyQww5UWC1A8utqqCafV3EKsIoaph+B6I/nvgIdE81AtBRCtaemWskJT4B7XLCGGxkhAgQa0OFcCsfV3ai8Hzp3HrBgWVSYoRNMdULuDZQXQ7Yhnzv7Dc1lMBt/A4yO9pwU8HaVPlULZQWGOfgcXR2UX0Py5aMIKLc8ZW+rvU89SKbedOylcyyTyaxeUzuUIT/S1zJKtLRCT3SgZAp6SmjtuZgEJmD7pTgIP8+HA9Pb+A5ZToPkek3IaRbnAhfZ432IGVKVb9U1ZCUrvuETOT+qjC+/JDnohvwIpK8ijyQX11soTts4qDJA91VVwcBgB48Wcwh9q11+mqEXJ1xNgsBEInsLXcCtikRb1hMC6K5ch11vdvJN31LqfpkrYqQM2iIPbFifYaJHNvBDEDk26oBBs6TRoR7SSwUhPewmHv3DhgNsGW6v+jG/+VhboKFKDFX/SZD2R2LwWw2MNkmUBn9QeKQrSxA0=
  secret_access_key:
    secure: hiMYXyW3jCZYf5ytmlMali149hV5fDhDh/KZY/Cmh4EsbWHgV7/TqhhDRg+k6hVYoxUO0cND8HUlCOWJgXKJuz/rU6PThgTXO+KSG6wLVCcxKw8oU8MW/UyhAWX3JTqtfjERrf28sCk7ZbF3StOUUqYJy3hdfDWbrYRC7BUlX7nAM+vNlnFm6rldX+4rIJvU7CGGoQyTOeT83BdCmu6hx7lB+foMgI+Gr5uOi4AZncML5JVPMwAVI6gZ9qYJUVKwf2W+05akYNQY77b/2rW4qXxdEmgU4gV4R0SUEYG2SirET1y1EHrmrBrVA/Sxzz1Nuwn69kDJPmb983fB4f2h6l3+2WcY2zVj5t0guxHpmsKerJMn73AaHjkWfCNlyyhFpvQquRQqjfLniCgJn4XjUPMP4jw7Zk9oMltiJaGBDmvIZ/ZERE0b/A+i84Fdkm6o+5MjuK/Ld45tpGr20SWEWZmQQK05FHY/Q5thSvmOljW+uJsk2Z16lvWYY2IMHPhJbICsQa50mXvPyjBQQs6zAKPHDOj82y1/kqlVKNrSyhq8v+RjAqGXD4tN4SkIl66i2ySnrO5aWHU/WJY4atLMlw8oNX0nQbcG4iz3WwbzAh++UvNNSmIjSklGWzPrJ+j09TjTqxpou9GmyDWHa3ZBKQ34iXaCdjWIAZ3W7vjwEpA=
  region: us-west-2
  app: brdgme-websocket-server
  env: brdgme-websocket-server-prod
  bucket_name: brdgme-websocket-server
  skip_cleanup: true
